name: EventCatalog Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  schema_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - uses: actions/checkout@v4
      - uses: event-catalog/github-action@main
        with:
          task: schema_review
          failure_threshold: 50
          provider: openai
          model: gpt-4o
          api_key: ${{ secrets.OPENAI_API_KEY }}
          license_key: ${{ secrets.EVENT_CATALOG_LICENSE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # catalog_directory: my-catalog
          # api_key: ${{ secrets.GOOGLE_API_KEY }}

      