name: EventCatalog Governance Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  governance:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - name: Checkout code

      - name: Run schema review checks for EventCatalog
        uses: event-catalog/github-action@main
        with:
          task: schema_review
          failure_threshold: 50
          provider: openai
          model: gpt-4o
          api_key: ${{ secrets.OPENAI_API_KEY }}
          license_key: ${{ secrets.EVENT_CATALOG_LICENSE_KEY }}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # catalog_directory: my-catalog
          # api_key: ${{ secrets.GOOGLE_API_KEY }