name: EventCatalog Governance Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  governance:
    runs-on: ubuntu-latest
    # Add this permissions block:
    permissions:
      pull-requests: write # Required to allow the action to post comments on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run schema review checks for EventCatalog
        uses: event-catalog/github-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          task: schema_review
          failure_threshold: '50'
          api_key: ${{ secrets.OPENAI_API_KEY }}
          provider: openai
          model: o4-mini
          license_key: ${{ secrets.EVENT_CATALOG_LICENSE_KEY }}
          # catalog_directory: my-catalog
          # api_key: ${{ secrets.GOOGLE_API_KEY }}

      